version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ttt
      POSTGRES_PASSWORD: ttt
      POSTGRES_DB: ttt
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
